/**
 * The supported target-platform ids, declared once.
 *
 * Every tool input schema that accepts a platform builds its `z.enum` from this
 * array, so adding a platform is one edit here rather than one edit per tool.
 * The duplication this replaces failed silently: a missed array left some tools
 * accepting the new platform and others rejecting it as an invalid enum value,
 * with the build and the suite both still green.
 *
 * Order is the order a client sees in an enum's error message and in generated
 * schema docs, so it is deliberate rather than incidental.
 *
 * Two other enumerations of the same set exist and are deliberately NOT derived
 * from this one, because each is an independent source whose agreement is worth
 * checking rather than assuming:
 *
 * - `INSPECTOR_PLATFORMS` in `inspector-types.ts`, generated by
 *   `npm run sync-compliance` from the dashboard. Spreading this constant into
 *   it would make the two agree by construction and erase the evidence of a
 *   real cross-repo disagreement.
 * - The platform columns of the support matrix in the `api/overview` doc, parsed
 *   at request time by `parseCapabilityMatrix`.
 *
 * `test/platforms.test.ts` asserts this constant against both, in both
 * directions.
 */
export const SUPPORTED_PLATFORMS = [
  "poki",
  "crazygames",
  "yandex",
  "gamedistribution",
  "youtube",
] as const;

export type SupportedPlatform = (typeof SUPPORTED_PLATFORMS)[number];

/** True when `value` is one of the supported platform ids. */
export function isSupportedPlatform(value: string): value is SupportedPlatform {
  return (SUPPORTED_PLATFORMS as readonly string[]).includes(value);
}
